# Fast runner (trick from @y0ssar1an) (out-dated)
sudo: false

# Language of deployment
language: go

# Version
go:
 - 1.23.x

# Environment variables
env:
 - GO111MODULE=on

# Only clone the most recent commit
git:
 depth: 1

# Notifications off
notifications:
 email: false

# Services required
services:
 - redis
 - mysql

# Run scripts in parallel
script:
 - make test-short