// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schema

var TableNames = struct {
	Auths   string
	Persons string
}{
	Auths:   "auths",
	Persons: "persons",
}
