// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schema

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Auths", testAuthsUpsert)

	t.Run("Persons", testPersonsUpsert)
}
